### ISSUE TITLE
Add "Open Government Licence"

### ISSUE THREAD

**Issue by smileygingerbread** [spdx/license-list#10]
I think this is a free license, but I don't see it on the list https://en.wikipedia.org/wiki/Open_Government_Licence

**Comment by jlovejoy** [comment]
there was a request to add this license (maybe from @mlinksva ?) There appeared to be multiple versions of the license and we try to add all versions of a license, but needed a bit more info (Which was apparently never obtained / followed up on).  Leaving this issue open to address with next rev

**Comment by mlinksva** [comment]
Not that I recall, though I do occasionally suggest to others to get an SPDX id (e.g., it's a [requirement](https://github.com/github/choosealicense.com/blob/422a0d113d41691c7d4b5ddcce37c05bcfd2ffa5/CONTRIBUTING.md#adding-a-license) for choosealicense.com).

There are a bunch of licenses going by OGL name, some of them listed at http://opendefinition.org/licenses/#other-conformant-licenses but by far the best known and original use of name AFAIK are the UK ones, of which there are 3 versions, as the linked Wikipedia article states.

**Comment by jlovejoy** [comment]
closing here, as added as issue in new repo here: https://github.com/spdx/license-list-XML/issues/547
