### ISSUE TITLE
Add "Open Data Commons Attribution License" from the Open Knowledge Foundation

### ISSUE THREAD

**Issue by smileygingerbread** [spdx/license-list#12]
https://opendatacommons.org/licenses/

**Comment by jlovejoy** [comment]
already have https://spdx.org/licenses/PDDL-1.0.html and https://spdx.org/licenses/ODbL-1.0.html - but seem to have missed https://opendatacommons.org/licenses/by/ - it may not have been in existence when we added the others, as that was early on.

**Comment by jlovejoy** [comment]
closing here, as logged this in new repo here: https://github.com/spdx/license-list-XML/issues/548
