### ISSUE TITLE
Add JavaScript (BSD 1-clause) license

### ISSUE THREAD

**Issue by grv87** [spdx/license-list#13]
Don't see this license in the list. Could you add it?
* https://urchin.earth.li/~twic/The_Amazing_Disappearing_BSD_License.html
* https://web.archive.org/web/20161018094742/http://slinq.com:80/blog/2011/12/31/the-1-clause-bsd-license-javascript-license/

**Comment by waldyrious** [comment]
You might be find the discussion at https://github.com/github/choosealicense.com/issues/464 interesting (see also https://github.com/david-a-wheeler/spdx-tutorial/issues/1)

**Comment by jlovejoy** [comment]
@grv87  - can you provide the information for "submission requirements" as described on this page https://spdx.org/spdx-license-list/request-new-license in this Issue? (We are in midst of moving old process for requesting a new license to Github issue, but have yet to define that completely!) thanks.

**Comment by jlovejoy** [comment]
closing issue, as this has been dealt and license set to be added via XML repository
