### ISSUE TITLE
Add Eclipse Public License 2.0 (EPL-2.0)

### ISSUE THREAD

**Issue by waynebeaton** [spdx/license-list#16]
The EPL-2.0 has been approved by the OSI and the Eclipse Board of Directors. We'd obviously like to see it included in the SPDX license list. FWIW, we're updating our legal documentation requirements to make heavy use of SPDX.

1. - License name: Eclipse Public License 2.0
2. - Proposed Identifier: EPL-2.0
3. - URL: https://www.eclipse.org/legal/epl-2.0/
4. - The license is OSI-approved
5. - The Eclipse OMR and Eclipse OpenJ9 projects are both currently switching over to the new version and we expect numerous other existing Eclipse projects do so as well.
6. - The Eclipse Foundation is investing in the use of SPDX and since we expect many/most of our projects to update to the new version of the license, having representation in SPDX is critical path.

The wrinkle, I think, is that there is a provision in the license for "secondary license" support. A project team may opt to declare that their project code is GPL compatible. I believe that this means that GPL compatibility is an exception; this is compounded by the ability to include various exceptions to the GPL.

The OpenJ9 project, for example, will be EPL-2.0 with GPL-2.0+CPE+AE. I think that this would manifest something like this:
EPL-2.0 WITH (GPL-2.0 WITH Classpath-exception-2.0 WITH Assembly-exception-2.0)

I'm a little concerned that I don't see Assembly-exception-2.0 on the exceptions list. I assume that this means that I'll have to shepherd this exception through as well.

Is this syntax even supported?

**Comment by waynebeaton** [comment]
For completeness, the Eclipse Foundation is tracking our side of this discussion in our issue tracker:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=520113

The Bugzilla record is basically a placeholder/pointer; I assume that the interesting discussion will happen in this GitHub Issue record.

**Comment by wking** [comment]
On Mon, Aug 21, 2017 at 09:28:58PM +0000, Wayne Beaton wrote:
> I assume that the interesting discussion will happen in this GitHub
> Issue record.

I'm not an SPDX maintainer, but I think the canonical channel for
proposing new licenses is the spdx-legal@ mailing list [1].  Once [2]
becomes canonical, I wouldn't be surprised if GitHub PRs become a
channel for proposing licenses, but we aren't there yet.

SPDX maintainers, a CONTRIBUTING.md in these repositories that links
out to [1] and similar is probably a good idea to make that
information more discoverable.  I'm happy to file PRs to that effect
if they sound useful.

[1]: https://spdx.org/spdx-license-list/request-new-license
[2]: https://github.com/spdx/license-list-XML/

**Comment by waynebeaton** [comment]
Well rats. I misread the comment regarding process on issue #13.

**Comment by jlovejoy** [comment]
@wking  is correct as to process, but this is already been suggested to be added and will be added, just need to make sure details are sorted/finalized.  

And yes, we need to update our documentation across the board as to how to contribute and other things.  I"m sort of leaving this as a whole-sale update for the next release for the XML files, since it kind of goes together... hopefully soon...

**Comment by jlovejoy** [comment]
License has been added in XML repository (which will become the master files for the 3.0 release), so closing this issue here.
