### ISSUE TITLE
Sendmail broken link

### ISSUE THREAD

**Issue by sharpaper** [spdx/license-list#17]
License: https://spdx.org/licenses/Sendmail.html

The link http://www.sendmail.com/pdfs/open_source/sendmail_license.pdf is broken.

**Comment by wking** [comment]
On Sat, Sep 30, 2017 at 04:05:42PM -0700, sharpaper wrote:
> The link
> http://www.sendmail.com/pdfs/open_source/sendmail_license.pdf is
> broken.

I've filed spdx/license-list-XML#436 with an additional (working)
Internet Archive URL.
