### ISSUE TITLE
CC0-1.0 optional "Creative Commons Legal Code" line?

### ISSUE THREAD

**Issue by mlinksva** [spdx/license-list#5]
https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt begins with a "Creative Commons Legal Code" line that isn't included in https://github.com/spdx/license-list/blob/788e54b566dc78358e3e1c3f9b7187ad4005114e/CC0-1.0.txt

I wonder if it should be included, marked as Optional?

I noticed this in comparing various versions at https://github.com/github/choosealicense.com/pull/488

Happy to send this to a mailing list if that's preferred (maybe this should be documented in README?) and this is worth discussing at all.

**Comment by mlinksva** [comment]
Another CC0-1.0 nit: it does have a standard file header, documented at https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

**Comment by jlovejoy** [comment]
re: the standard header: that is interesting, as I had not seen that before. As per our field definition of standard header (https://spdx.org/spdx-license-list/license-list-overview) we stated: "Should only include text intended to be put in the header of source files or other files as specified in the license or license appendix when specifically delineated" - which is pretty narrow, as it would exclude information such as this which is included in a separate document.  
Given the documentation comes from Creative Commons, I'd be inclined to add it, but would like to hear what others think (and if so, we'd need to update the field definition/description)
@pmadick @bradleeedmondson - thoughts?

**Comment by wking** [comment]
> Given the documentation comes from Creative Commons, I'd be inclined to add it, but would like to hear what others think (and if so, we'd need to update the field definition/description)

I agree that we want to include the CC's recommended header somewhere.  I'm fine with updating the docs for the [Standard License Header][1] to be based instead on the license author/maintainer's recommendations, regardless of the source location, although note that we [do not currently track author/maintainer information][2], so in some cases “does $AGENT have permission to provide a new standard header for $LICENSE?” may become sticky.  If we want to avoid that, we can always drop whatever we want in the less-structured notes, but then tooling which is using the standard header for matching may not benefit.

[1]: https://spdx.org/spdx-license-list/license-list-overview
[2]: https://github.com/spdx/license-list-XML/pull/83#discussion_r102840700

**Comment by jlovejoy** [comment]
closing this, as dealt with in XML repo
