### ISSUE TITLE
Inconsistent use of "only" in "Full Name of License" column

### ISSUE THREAD

**Issue by mlinksva** [spdx/license-list#6]
GPL-3.0 gets "GNU General Public License v3.0 only" and GPL-1.0, GPL-2.0, LGPL-2.0, LGPL-2.1, and LGPL-3.0 likewise, but no other licenses that do not by default permit other versions have this naming convention. 

The most glaring inconsistency is with AGPL and GFDL licenses which have the same text presumably inspiring "only". But again, there are other licenses that don't allow use of other versions, and though they don't include instructions for doing so, one could separately grant permission to use future versions.

The easiest and most consistent thing to do would be to drop "only" from any license names in the "Full Name of License" column, it seems to me. However, I'm probably missing some previous decision on the matter.

**Comment by wking** [comment]
On Sat, Mar 04, 2017 at 01:48:31PM -0800, Mike Linksvayer wrote:
> The easiest and most consistent thing to do would be to drop "only"
> from any license names in the "Full Name of License" column, it
> seems to me. However, I'm probably missing some previous decision on
> the matter.

I am also unfamiliar with the context but feel like “only” should be
dropped [1].  It's part of how the project applies the license, not
part of the license itself.

[1]: https://github.com/spdx/license-list-XML/pull/83#discussion_r102838766

**Comment by jlovejoy** [comment]
Hi, sorry, just saw this now... having trouble keeping up with various threads now.  The short answer is that there is a long backstory for why "only" is there that dates back to the creation of the SPDX License List and before we had the license expression syntax. But this is a good reminder that we ought to review this in the current day situation. This is a topic that is more easily discussed on a call, so I will make a note for next meeting on April 13, hope you can both join!

**Comment by jlovejoy** [comment]
part of bigger discussion being tracked here: https://wiki.spdx.org/view/Legal_Team/or-later-vs-unclear-disambiguation

**Comment by wking** [comment]
On Thu, Jun 08, 2017 at 09:25:08PM -0700, Jilayne Lovejoy wrote:
> part of bigger discussion being tracked here:
> https://wiki.spdx.org/view/Legal_Team/or-later-vs-unclear-disambiguation

I think we can address *this* bit independently.  That wiki page and
the thread starting with [1] are about the Short Identifier and/or
License Expression syntax.  This issue can be about the narrower,
~~unrelated~~ indirectly-related, human-readable name.  I don't
expect us to end up with multiple Short Identifiers for the same
license text, so there's no need to distinguish between “only” and
“or later” forms in the license name.  Whichever SPDX license entry
has the FSF's recommended [2]:

  … either version 3 of the License, or (at your option) any later
  version.

notice should not have “only” in the full license name.

If SPDX wants to carry a custom only-this-version notice despite the
FSF's stock recommendation, I think we'd want to decouple the notices
from the licenses.  Then we can have “only” and “or later” notices
(matching whatever license expression the wiki and [1] settle down to)
which share the same license (with a non-only name).

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-May/001973.html
[2]: https://www.gnu.org/licenses/gpl-3.0.en.html#howto

**Comment by jlovejoy** [comment]
closing this issue, as it is already captured in new/XML repo with reference back to this discussion
