### ISSUE TITLE
ISC copyright and URL

### ISSUE THREAD

**Issue by mlinksva** [spdx/license-list#7]
The ISC license template here has hardcoded ISC as the copyright holder. That's not how it's used in practice, other than by ISC. There are licenses with a hardcoded copyright notice for the license text, but I don't think ISC is one of those. I think the copyright line should be similar to MIT or the BSDs here -- to be replaced with the licensor's info, and as shown at https://opensource.org/licenses/ISC

Noticed discrepancy at https://github.com/github/choosealicense.com/pull/489#issuecomment-284270176

Also, the ISC URL for the license has moved from https://www.isc.org/downloads/license to https://www.isc.org/downloads/software-support-policy/isc-license/ unfortunately without a redirect.

**Comment by jlovejoy** [comment]
I just updated the broken link in the new/XML repo here: https://github.com/spdx/license-list-XML/tree/master/src  
As for the copyright notice, that is now taken care of via the new XML markup - that is, it will have the copyright tag which indicates it is replaceable. in which case, I'm not sure it matters what the "original" text is.  
Does that sound okay?

**Comment by mlinksva** [comment]
@jlovejoy it's OK if the copyright tag indicates the text is replaceable, but I think it'd be more clear if the text also signaled that eg in https://github.com/spdx/license-list-XML/blob/2e89b5e28fb1b24efc70f87bad853dcd1ba6ded5/src/MIT.xml#L10 ... whether copyright notices pertain to the license text or the licensed material is something people easily get confused by in my experience.

Knowing that the copyright tag is meant to be replaced (and thus only useful for notices for the licensed material, not the license text), I suspect https://github.com/spdx/license-list-XML/blob/2e89b5e28fb1b24efc70f87bad853dcd1ba6ded5/src/Artistic-2.0.xml#L11-L13 should not be in a copyright tag. But it is possible that I am among the [confused](https://github.com/github/choosealicense.com/issues/310#issuecomment-159096032).

(Happy to continue/open issues in the XML repo; I didn't realize until now that it must be where work on the immediate next version is being done.)

**Comment by jlovejoy** [comment]
closing this, as @bradleeedmondson has moved issue to xml repo, so we can address as needed there for next release.  

thanks for your patience generally, @mlinksva :)
