### ISSUE TITLE
Update URL of ECL License?

### ISSUE THREAD

**Issue by buckett** [spdx/license-list#8]
Currently the ECL license in this repository (https://github.com/spdx/license-list/blob/master/ECL-2.0.txt) has a URL (http://osedu.org/licenses/) in it that doesn't take you to a copy of the license.

Is this something that:
- Matters?
- Can be fixed?
- Should be fixed?

I think the domain osedu.org didn't get re-registered and someone else has control of it now who doesn't have the license page up.

**Comment by mlinksva** [comment]
It's noted in the spreadsheet:

> The url included in the boilerplate notice does not work. (15/10/10)

Seems to me it matters as both URLs (other being the OSI one) can be found in the wild, OSI one becoming more common as [people replace so URL works](https://github.com/sakaiproject/sakai/commit/18353f5d3b85f632a014dfdba3a86c8e5517e4fe), and it'd be nice if these were used in matching.

I see SPDX markup allows for replaceable and omittable text, but not lists of acceptable values. I guess making the URL replaceable would be a decent workaround.

**Comment by mlinksva** [comment]
I'm wrong, it seems lists of acceptable values can be achieved with the match directive, there's one license that uses it, `RSA-MD.txt`:

```
<<var;name=algorithm;original=MD5;match=(MD5|MD4)>>
```

**Comment by jlovejoy** [comment]
In this case, the url is in the license text, but in a section that is already marked as optional, so I don't think it effectively matters. Given it is part of the "original text" of the license (and doesn't impact matching), I'm inclined to leave it be.
