### ISSUE TITLE
NCSA formatting

### ISSUE THREAD

**Issue by mlinksva** [spdx/license-list#9]
https://github.com/spdx/license-list/blob/788e54b566dc78358e3e1c3f9b7187ad4005114e/NCSA.txt#L5

```
Developed by: <<var;name=organization;original=<Name of Development Group> <Name of Institution> <URL for Development Group/Institution>;match=.+>>
```
It seems everywhere else these are on separate lines, eg

- http://otm.illinois.edu/disclose-protect/illinois-open-source-license
- https://opensource.org/licenses/NCSA
- https://github.com/llvm-mirror/lldb/blob/master/LICENSE.TXT

Should the SPDX template add newlines between each of the "Developed by" fields?

**Comment by jlovejoy** [comment]
in terms of matching, this won't matter as any white space is treated the same.  If this is an aesthetic issue, we can certainly change it to look better!

**Comment by mlinksva** [comment]
I'd like it to look better/like it does as used in the wild.

Reason: I'd [like](https://github.com/github/choosealicense.com/issues/463) to use SPDX as a canonical collection of license texts, not only for matching, but for use, and I'd like to use texts from that collection with a minimum amount of application-specific munging. But maybe this is totally unimportant to SPDX and it should ignore anything that doesn't improve matching.

**Comment by jlovejoy** [comment]
moved to an issue in xml repo, so this gets addressed there :)
